### ISSUE TITLE
stripeConfig.json

### ISSUE THREAD

**Issue by leo-coco** [fromAtoB/vue-stripe-elements#1]
Hello,

I have hard time to figure out what include in `stripeConfig.json`and what is the correct structure.

Could you help me out ? 

Thank you

**Comment by chip** [comment]
@leo-coco - I was able to get it to work by renaming the file to `stripeConfig.js` and using something like this:

```
export const stripeKey = 'pk_test_XXXXXXXXXXXXXXXXXXXXXXXX'
export const stripeOptions = {}
```
I will eventually fill in my `stripeOptions` per Stripe's docs, but wanted something basic to get it working.

I was also getting eslint errors unless I returned `stripeKey` and `stripeOptions` from the `data` function. BTW, it's a typo in the example. See #4.

HTH
-Chip

**Comment by nkoehring** [comment]
Githubs Notifications once worked for me but this time I didn't get any message. Sorry for the late reply.

To include `stripeConfig.json` into a (for example webpack based) project, you need a [loader that can handle and directly include JSON files](https://github.com/webpack-contrib/json-loader).
Of course you don't really need to use something like this. It is only important to have the Key and Options somewhere and I found the JSON file handy for my example.

Instead, just write them directly into the attributes if you want:

```jsx
    <card class='stripe-card'
      :class='{ complete }'
      stripe='pk_test_XXXXXXXXXXXXXXXXXXXXXXXX'
      :options='{some: "options"}'
      @change='complete = $event.complete'
    />
```

The options are exactly the ones described [here in the documentation](https://stripe.com/docs/stripe.js#element-options).

I hope I could help.

**Comment by adamprocter** [comment]
Would be great if there was example stripConfig.json as part of the readme, I couldn't get it to work.

**Comment by nachomozo** [comment]
I have the `stripeConfig.json` file in `src` folder with the following content:

```json
{
  "stripeKey": "pk_test_xxxxxxxxxxxxxxxxxx",
  "stripeOptions": {
    "hidePostalCode": true
    ...
  }
}
```

And then in my component I have it imported that way:
```javascript
 import { stripeKey, stripeOptions } from '@/stripeConfig.json'
```

I need this data variables too:
```javascript
data: function () {
    return {
        stripeKey: stripeKey,
        stripeOptions: stripeOptions
    }
}
```

That works for me.
