### ISSUE TITLE
`createToken` error with multiple elements example

### ISSUE THREAD

**Issue by samtsai** [fromAtoB/vue-stripe-elements#10]
Hi!

I'm having issues creating a token when implementing multiple elements. Rendering and validation are fine, but when I trigger the request it reports that I have an invalid number. It seems like the request is not sending the full set of details. 

**Request:**
`card[cvc]:123`
...

**Response:**
```
{
  "error": {
    "message": "The card object must have a value for 'number'.",
    "type": "card_error",
    "param": "number",
    "code": "invalid_number"
  }
}
```

I've been comparing the request sent in Stripe's example here: https://jsfiddle.net/ywain/o2n3js2r/ 
and their request correctly passes the other values: `card[number]`, `card[exp_month]`, `card[exp_year]`.

**Comment by samtsai** [comment]
@nkoehring @jorngeorg any thoughts on this?

**Comment by nkoehring** [comment]
@samtsai I just realised that we have the same problem in an (unmerged) branch. A fix will be shipped soon.

**Comment by nkoehring** [comment]
@samtsai I used your PR right away. Works like a charme on my side. Version 0.2.2 is published.
