### ISSUE TITLE
Electron: Live Stripe.js integrations must use HTTPS

### ISSUE THREAD

**Issue by fsproru** [fromAtoB/vue-stripe-elements#105]
Hi there, just noticed that once we mount `Card` component in our Electron app, it throws the following error:

```
Live Stripe.js integrations must use HTTPS. For more information: https://stripe.com/docs/web/setup#http-requirements
```

Looks like Stripe treats the environment as a non HTTPs environment when running inside Electron. Is there a way to solve it in `vue-stripe-elements` so it's usable for Electron apps?

Thanks,
Alex

**Comment by Bubblex** [comment]
this error appears when you use a Live Mode publishable key with Stripe.js in an environment that isn't being served over HTTPS. In your case, it sounds like you're working in a local environment without HTTPS. This error won't appear if you use a Test Mode key in your development environment.

You can find your test mode publishable key on your dashboard, or by checking out this page while logged in to Stripe: https://stripe.com/docs/keys#api-keys

I hope that helps to clear things up!

**Comment by fsproru** [comment]
Thank you. Also talked to Stripe support and looks like they don’t support
running Stripe inside an Electron app. They recommend putting the form on
the web instead. Just wanted to share it here in case someone else runs
into the same issue with Electron.
