### ISSUE TITLE
can't call methods in "mounted()" when using vue-stripe-elements

### ISSUE THREAD

**Issue by iamgoodbytes** [fromAtoB/vue-stripe-elements#13]
Hi!

I have a method called getPreferences() that loads up some user data I want to show in the view. Calling this function however, triggers the following error. When I remove the reference to this.getPreferences() in the mounted() function, all works fine. 

```
mounted() {
            this.getPreferences();
},
```

`[Vue warn]: Error in beforeMount hook: "IntegrationError: Can only create one Element of type card."`

`[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'mount' of undefined"
found in
---> <StripeElement>
       <Card>`

When I don't use the Card component, calling my own method in mounted() also works fine. Thanks for helping out!

**Comment by iamgoodbytes** [comment]
Seems to be related to the naming of my data, when using "preferences" in my data it crashes, but if I rename that it works. Might be some sort of naming collision?

**Comment by mikerogerz** [comment]
I'm pretty sure this only started happening since commit dae20d15f127c904356457b068d1e4ceb8b5e57f

**Comment by nkoehring** [comment]
Should be fixed in the current published version (commit https://github.com/nkoehring/vue-stripe-elements/commit/a4b8fbc02db5af87c0ac760ad284e94554cc79aa, version 0.2.3 on npm: https://www.npmjs.com/package/vue-stripe-elements)

**Comment by nkoehring** [comment]
@softbeehive it looks like the patch reached the base repository a while ago already. If you confirm, you can close this PR.
