### ISSUE TITLE
Unable to create token if component is unmounted and then mounted again

### ISSUE THREAD

**Issue by mikerogerz** [fromAtoB/vue-stripe-elements#2]
My <card> component is shown within a modal overlay (which is shown or not based on other page actions), and when opening the modal after the first time, the token can't be created since the element is undefined (the card entry field is displayed correctly, which means Stripe is loaded correctly). Just to be clear, the token is correctly generated on the first display of the component.

Once thing I already tried was dynamically loading the component when the modal is displayed, but that resulted in the same behaviour. I thought that might help to remount the Stripe element and reset everything.

**Update:**
Reference pull request: #3

**Comment by nkoehring** [comment]
Thanks @mikerogerz for your report and the PR! Next release with fixes will be out it 3… 2… 1…
