### ISSUE TITLE
PostalCode does not use the correct events

### ISSUE THREAD

**Issue by paulpdaniels** [fromAtoB/vue-stripe-elements#24]
The `PostalCode` component has a bunch of events defined on it but none of them match up with what is being fired from the underlying `StripeElement`. 

Most notably the "change" event is missing (instead there is `complete` but there doesn't appear to be any logic to actually emit that).

Also could you export the `StripeElement` as part of the `lib` build? It isn't part of the exports it is isn't even possible to create a custom `StripeElement` to work around the buggy `PostalCode`.

**Comment by softbeehive** [comment]
Should be fixed in v0.2.7
