### ISSUE TITLE
Unrecognized create() parameter: elements is not a recognized parameter

### ISSUE THREAD

**Issue by padi** [fromAtoB/vue-stripe-elements#31]
https://github.com/fromAtoB/vue-stripe-elements/blob/d4255af6da782801b9fcf2a8b83238f0c7ad2c58/src/stripeElements.js#L48

While we seem to use `elements` to pass along options for `stripe.elements`, there's a warning when it gets passed unto `elements.create`

```
Unrecognized create() parameter: elements is not a recognized parameter. This may cause issues with your integration in the future.
```

Sample browser error:
<img width="818" alt="screen shot 2018-03-01 at 12 30 33 pm" src="https://user-images.githubusercontent.com/807110/36827016-f1b8ecac-1d4b-11e8-8664-7ce44bd6af49.png">

**Comment by kushbhandari** [comment]
+1

**Comment by NSpehler** [comment]
Did you ever find a workaround to avoid this warning?

**Comment by paynegreen** [comment]
To apply parameters like `style`, use this format ```options: {
        style: {
          base: {
            color: 'red'
          }
        }
      }```

**Comment by AndrianD** [comment]
> To apply parameters like `style`, use this format `options: { style: { base: { color: 'red' } } }`

what does this have to do with the reported bug?

**Comment by AndrianD** [comment]
I don't see any difference in the old and the new code ?




Le mar. 17 sept. 2019 à 11:03, Ian Jamieson <notifications@github.com> a
écrit :

**Comment by ianjamieson** [comment]
Sorry I removed my comment as it wasn't actually relevant to the original error, but just in case anyone stumbles across the same error I was getting:

```
Unrecognized create() parameter: betas is not a recognized parameter. This may cause issues with your integration in the future.
```

Then this fixed it for me:

We had switched on payment_intent_beta_3 in the past. Which now seems like a redundant flag.

Original code:
```
Stripe('1234', {
betas: ['payment_intent_beta_3']
});
```

Changed to:
```
Stripe('1234');
```

Fixes the error

**Comment by sedrickcz** [comment]
As we are using from v3.0.0 Payment intent, this should not happen anymore.
