### ISSUE TITLE
how to remove "zip code field" ?

### ISSUE THREAD

**Issue by BostonKenne** [fromAtoB/vue-stripe-elements#33]
![image](https://user-images.githubusercontent.com/19219342/38031235-0fc32f46-329b-11e8-9ff4-c33e32887a4b.png)
I'm trying to remove a zipcode field, please can you help?

**Comment by softbeehive** [comment]
Hi @BostonKenne, it depends on how you use it. 
1. If you use `<card />` element: zip code presence is determined by stripe library that takes into account the card number
2. You can use multiple elements, example available in readme https://github.com/fromAtoB/vue-stripe-elements#multiple-elements
