### ISSUE TITLE
Nuxt.js, <script> loaded, but throws "Cannot read property 'elements' of undefined"

### ISSUE THREAD

**Issue by koresar** [fromAtoB/vue-stripe-elements#35]
The example from README doesn't work if you put it to a **not the index page** of a Nuxt.js project. 

* Create nuxt.js project
* Add the README example to a not the index page
* Navigate from index the that new page. -> console is full of errors.
```
TypeError: Cannot read property 'elements' of undefined
    at n (index.js:60)
    at r (index.js:65)
    at VueComponent.beforeMount (index.js:129)
    at callHook (vue.runtime.esm.js:2891)
    at mountComponent (vue.runtime.esm.js:2738)
    at VueComponent.webpackJsonp../node_modules/vue/dist/vue.runtime.esm.js.Vue$3.$mount (vue.runtime.esm.js:7891)
    at init (vue.runtime.esm.js:4061)
    at hydrate (vue.runtime.esm.js:5892)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js:6007)
    at VueComponent.Vue._update (vue.runtime.esm.js:2633)
```

I debugged it down to the `init()` function in `src/stripeElements.js`. If I put in it
```
console.log(window.Stripe)
```
then it prints the stripe factory. So, I'm 100% Stripe was loaded by that time. And I can see it in the `<head>`.

I cannot figure out how to fix initialization to make it work.

Any workarounds are welcome too.

Please, help.

**Comment by koresar** [comment]
Found a workaround.
1) Do not add stripe v3 `<script>` to your **index.html** as README suggests.
2) Do not display `vue-stripe-elements-plus` components. Hide them behind `v-if`.
3) Load the stripe v3 script dynamically on the `created()` or `mounted()` Vue hook. E.g.:
```
    created () {
      if (process.browser) {
        let domElement = document.createElement('script')
        domElement.setAttribute('src', 'https://js.stripe.com/v3/')
        domElement.onload = () => {
          this.loadedStripe = true
        }
        document.body.appendChild(domElement)
      }
    },
```
4) Show the `vue-stripe-elements-plus` components previously hidden behind the `v-if`. See `this.loadedStripe = true` above.

Hope this helps someone else.

**Comment by softbeehive** [comment]
Thank you for sharing details of your issue and the workaround. Unfortunately Nuxt.js support is missing in `vue-stripe-elements@0.x` but we will consider adding it in next major version.

**Comment by CoolFullstackDev** [comment]
It really saved my day. Thanks

**Comment by rlindskog** [comment]
Able to get it to work using [`<NoSsr>`](https://nuxtjs.org/api/components-no-ssr#the-lt-no-ssr-gt-component)

Example
```vue
<template>
  <div>
    <NoSsr>
      <CardNumber stripe="YOUR_KEY"/>
    </NoSsr>
  </div>
</template>

<script>
import { CardNumber } from 'vue-stripe-elements-plus'

export default {
  components: { CardNumber }
}
</script>
```
