### ISSUE TITLE
iOS Safari Keyboard stay open after payment redirect

### ISSUE THREAD

**Issue by Xationch** [fromAtoB/vue-stripe-elements#38]
Hi,

After payment and redirection with vue-route the keyboard with number remains open. Even when I click on "ok" to close it, it comes back.

Do I have to do something at the time of the destroy? When I leave my Buy.vue component?

I notice this only with Stripe Elements.

**Comment by softbeehive** [comment]
Hi,
It's hard for me to reproduce this issue. It would be great if you share the code on `jsfiddle`. This would prove issue is caused by `vue-stripe-elements` and allow more people to investigate it.
Thanks

**Comment by Xationch** [comment]
Hi,

After further research it may not be related to Stripe Elements. It seems to work in my tests. The problem is apparently related to ios only.

```
	beforeDestroy () {
		document.activeElement.blur()
	}
```

Thank you for taking the time to answer me.
