### ISSUE TITLE
Load in Stripe V3 js for components

### ISSUE THREAD

**Issue by paulm17** [fromAtoB/vue-stripe-elements#39]
Thanks for developing these components for Vue.

I have a rather large and complex application.  I much prefer to lazy load in the components.  Having anything in index.html is out of scope for me.

Would it be possible to have the Stripe JS load in and be available to the components?

Or perhaps there is a better way of doing this?

	<template>
		<div>
			<div class='credit-card-inputs'>
				<async-component1></async-component1>
				<card-number 
					class='stripe-element card-number'
					ref='cardNumber'
					:stripe='stripe'
					:options='options'
				/>
				<card-expiry class='stripe-element card-expiry'
					ref='cardExpiry'
					:stripe='stripe'
					:options='options'
				/>
				<card-cvc class='stripe-element card-cvc'
					ref='cardCvc'
					:stripe='stripe'
					:options='options'
			    />
			</div>
		</div>
	</template>

	<script>
		const AsyncComponent1 = () => ({
			component: new Promise((resolve, reject) => {
				let script = document.createElement('script')
				script.src = 'https://js.stripe.com/v3/'
				document.head.appendChild(script)
			})
		})

		const CardNumber = () => ({
			component: new Promise((resolve, reject) => {
				setTimeout(() => {
					resolve(require('../../../../../node_modules/vue-stripe-elements-plus/src/CardNumber.vue'))
				}, 1000)
			})
		})

		const CardExpiry = () => ({
			component: new Promise((resolve, reject) => {
				setTimeout(() => {
					resolve(require('../../../../../node_modules/vue-stripe-elements-plus/src/CardExpiry.vue'))
				}, 1000)
			})
		})

		const CardCvc = () => ({
			component: new Promise((resolve, reject) => {
				setTimeout(() => {
					resolve(require('../../../../../node_modules/vue-stripe-elements-plus/src/CardCvc.vue'))
				}, 1000)
			})
		})

		export default {
			name: 'CreditCardForm',
			props: [ 'stripe', 'options' ],
			data () {
				return {
					complete: false,
					number: false,
				}
			},
			components: {
				'async-component1': AsyncComponent1,
				'card-number': CardNumber,
				'card-expiry': CardExpiry,
				'card-cvc': CardCvc			
			},
			methods: {				
				
			},
			watch: {
				
			}
		}
	</script>

	
	<style scoped>
	</style>

**Comment by softbeehive** [comment]
Hi @paulm17, good question!

I endorse the idea of lazy loading any external dependency as long as your cross-origin policy allows it.   However: there are pros and cons.

**Pros**
- save client's resources for critical data
- being in control which parts of the web app are exposed to external dependency (preventing tracking by third parties, protecting user data)
- potentially there are other benefits

#### Cons
- external dependency is hardcoded, so it is excluded from your build process
- Stripe's ability to monitor fraud. I don't whether it's true or not but here is what they say
> Including the script on every page allows Stripe to detect anomalous behavior that may be indicative of fraud as users browse your website.

#### What I can suggest regarding your example:
_Template_
```html
<async-component />
<div v-if="stripeLoaded">
  <card-number
    ...
  />
  <card-expiry
    ...
  />
  <card-cvc
    ...
  />
</div>
```

_Script_
```javascript
// you probably will need vuex or similar to keep the state of stripe loading
import { CardNumber, CardExpiry, CardCvc } from 'vue-stripe-elements-plus'

export default {
  components: { CardNumber, CardExpiry, CardCvc },

  computed: {
    stripeLoaded () {
      return this.$store.state.stripeLoaded
    }
  }
}
```

And in your `AsyncComponent` you will call the action that will commit mutation and set `stripeLoaded` property in your state. I hope it helps.

**Comment by paulm17** [comment]
Many thanks for your input.  I'm doing something different now and will close the ticket.
