### ISSUE TITLE
createSource type three_d_secure 

### ISSUE THREAD

**Issue by hakimdja** [fromAtoB/vue-stripe-elements#40]
Hello,

there is an error :  Uncaught (in promise) Error: Invalid value for type: value should be one of the following strings: card. You specified: three_d_secure.

in line 52 of stripeElements.js you do :
" Stripe.createSource = (options) => Stripe.instance.createSource(element, options) "
but there are 2 functions fore creating Sources : 
stripe.createSource(element, sourceData) and stripe.createSource(sourceData) 
doc : https://stripe.com/docs/stripe-js/reference#stripe-create-source

I corrected my code by accessing the instance to use the 2nd function

import { CardNumber, CardExpiry, CardCvc, createSource, instance } from 'vue-stripe-elements-plus'
create the card with first function: createSource(ownerInfo).then( ...
create three_d_secure with 2nd function: instance.createSource({  type: 'three_d_secure', ...

**Comment by sedrickcz** [comment]
It should be fixed now.
