### ISSUE TITLE
Issue on Iphones

### ISSUE THREAD

**Issue by alexander-v-ysbm** [fromAtoB/vue-stripe-elements#44]
https://drive.google.com/file/d/1-0r0pVA2bH14kf0G688tulQV_FfbiSB1/view?usp=sharing

Something wrogn when click to paste card number, client start send queries to get image
Safari

**Comment by chamby** [comment]
I am also seeing this behavior. It ends up locking mobile Safari completely.

**Comment by wgrabias** [comment]
It seems to happen only when displaying an element inside element changing focus (i.e. bootstrap modal)
setting (when modal's `focus` option is set to `false` the issue doesn't appear)

**Comment by mwargan** [comment]
I have not seen this behaviour. I'd think that your issue may be related to an external package.
