### ISSUE TITLE
How to make charges

### ISSUE THREAD

**Issue by Math823g** [fromAtoB/vue-stripe-elements#45]
Is it possible to create stripe charges with this library?
The way I see from the documentation, it only makes tokens (through createToken), and I want the test-payments to show up in my Stripe dashboard.

**Comment by mwargan** [comment]
As far as I understand, you can not create a charge here. You have to send the token to your backend, which will create the Stripe user. Then you can charge (again on the backend) as much as you want without the token, as it should be stored in your DB. Not the card token, but the Customer Token that will be returned from your backend.

**Comment by Math823g** [comment]
Alright then. Thank you very much for the information :)
