### ISSUE TITLE
 Error in mounted hook: "TypeError: Cannot read property 'mount' of undefined"

### ISSUE THREAD

**Issue by CyberStrike** [fromAtoB/vue-stripe-elements#57]
This error is currently occurring for `vue-stripe-elements-plus@0.2.9` maybe a regression as I see it 
 reported and was fixed in the past.

```
vue.common.js:593 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'mount' of undefined"

found in

---> <StripeElement> at /Users/fromatob/Projects/vue-stripe-elements/src/StripeElement.vue
       <CreditCard> at /Users/fromatob/Projects/vue-stripe-elements/src/Card.vue

```

**Comment by CyberStrike** [comment]
Additional Info it seems it has something to do with vue-router if I navigate to the page by URL the component does not mount successfully. But if I navigate to the view by router it mounts without error.

**Comment by laravelian** [comment]
I'm having this issue when using this package in a top-level component, not using vue-router anywhere in the project.

**Comment by butaminas** [comment]
Having the same problem. Anyone found what's causing it?

**Comment by AhmedOwaydat** [comment]
I used this script in index.html file after app div
<script src="https://js.stripe.com/v3/"></script>

this solved the problem.
