### ISSUE TITLE
Missing way to set options on Stripe object

### ISSUE THREAD

**Issue by jorngeorg** [fromAtoB/vue-stripe-elements#6]
Per the Stripe documentation, https://stripe.com/docs/stripe.js#the-stripe-object, it should be possible to set options such as locale and custom fonts on the Stripe element it self. 

Like so: `stripe.elements([options]). `

But this seems to be omitted in this plugin?

My suggestion would be something along the lines of:

`const element = Stripe.elements(options.elementStyle).create(elementType, options)`

**Comment by perkola** [comment]
Any progress on merging this PR? I would really like to be able to set options on the Stripe object itself.

**Comment by nkoehring** [comment]
@jorngeorg @perkola Thanks for your patience. I just merged the PR and will publish a new npm package during the course of the day.
