### ISSUE TITLE
Support for the hidePostalCode option

### ISSUE THREAD

**Issue by mydnic** [fromAtoB/vue-stripe-elements#60]
Hello,

In the Stripe documentation, there's a "hidePostalCode" property on the "Card" Element, allowing you to disable the postal code input.

Is this currently supported? Or can it be?

Thanks in advance!

**Comment by lanbau** [comment]
@mydnic yes it supports hidePostalCode. It works for me.

**Comment by mydnic** [comment]
You're right I managed to make it work.
This property must be set in the StripeOptions object and not on the card element directly

```javascrtipt
stripeOptions: {
    hidePostalCode: true
}
```
