### ISSUE TITLE
Support for Stripe Payment Intents

### ISSUE THREAD

**Issue by CromonMS** [fromAtoB/vue-stripe-elements#66]
Hi,

Great little component here, saving my bacon right now, any thoughts about supporting Stripe PaymentIntents?

https://stripe.com/docs/payments/payment-intents/quickstart
https://stripe.com/docs/stripe-js/reference#stripe-handle-card-payment

Seems you'd need support for the stripe.handleCardPayment() function.

Thanks

**Comment by CromonMS** [comment]
take a look here if you get a chance, I'm not entirely sure I have nailed it, and wont have a chance to test it right now: https://github.com/CromonMS/vue-stripe-elements/tree/adding-new-functions

**Comment by KaisNeffati** [comment]
This is a very important feature as it would takes effect starting septembre in all europe !
@sedrickcz when could we have this please ^^ !!

**Comment by stevehayles** [comment]
Please see pull request at https://github.com/fromAtoB/vue-stripe-elements/pull/74

Limited testing but working very well with the 2 main possible flows within the Payments Intent API

**Comment by coryrose1** [comment]
Just checking to see if there has been any update in integrating Payment Intents?

Laravel Cashier v10 no longer accepts a Stripe Token to create a card source.

**Comment by Teranode** [comment]
You also need to add `handleCardAction`

**Comment by sedrickcz** [comment]
With v.0.3.0 we are using Payment Intent API
