### ISSUE TITLE
using axios

### ISSUE THREAD

**Issue by trevorpan** [fromAtoB/vue-stripe-elements#81]
Hi,

I just gave vue-stripe-elements a go. 

When submitting the form I get a 
```
The POST method is not supported for this route. Supported methods: GET, HEAD, PUT, PATCH, DELETE.
```
error.

In the BidReserve.vue file should an axios call happen on the pay() method? I'm using laravel, and the token is being created on the backend, which is where I'm a bit in a grey area. If I cancel out the `createToken()` line I get the same result of not posting to the proper route.

Here's what I'm trying, but still get this error. The route being called `bidreserve` is defined in the routes web.php file.
```
        methods: {
            pay () {
                // createToken returns a Promise which resolves in a result object with
                // either a token or an error key.
                // See https://stripe.com/docs/api#tokens for the token object.
                // See https://stripe.com/docs/api#errors for the error object.
                // More general https://stripe.com/docs/stripe.js#stripe-create-token.


                createToken().then(data => console.log(data.token))

                this.processing = true
                axios.post('/jobs/${this.jobId}/bidreserve', {
                    amount: this.amount,
                    payment_token: token.id,
                }).then(response => {
                    window.location = `/orders/${response.data.confirmation_number}`
                }).catch(response => {
                    this.processing = false
                });
            },
```
Thank you for any tips ~

**Comment by dvlden** [comment]
From where are you getting your `token.id`? Assuming that should be coming from your `createToken()` method.

```
export default {
  // ..
  methods: {
      submit (e) {
        if (this.isTrialPlan) {
          this.register(e)
        } else {
          createToken().then(data => {
            if (data.error) return

            this.form.stripe_token = data.token.id
            this.register(e)
          })
        }
      },
      register (e) {
        this.processing = true

        this.$store.dispatch('auth/register', this.form)
          .then(response => { .. })
          .catch(response => { .. })
      },
}
```

**Comment by trevorpan** [comment]
Hi @dvlden 

I stepped away from this package for the past few weeks. Let me get back with you shortly...

Thank you!

**Comment by dvlden** [comment]
@trevorpan What's the reason and have you found a better alternative?
I am having issues with the whole SCA regulation and it's not that this package is not working, it's that I am not sure that I understand the process that BE must handle.

Can no longer register and charge in a single BE request.

Sorry for bits of off-topic. Let me know if you have any doubts regarding your issue.

**Comment by trevorpan** [comment]
Yea, not regulation related. I was not able to get the components working properly. So, I opted for stripe's vanilla js implementation. I've got it together now, creating tokens, etc. 

Vue components add a bit of complexity, and I'd just need a bit more time to sort that out ( beginner)

**Comment by sedrickcz** [comment]
Yeah, SCA regulation is pain. I just started cleaning and preparing this package for v1.0.0.. So hopefully it will be more useful in the future.
