### ISSUE TITLE
createPaymentMethod is not working.

### ISSUE THREAD

**Issue by BaiMaoLi** [fromAtoB/vue-stripe-elements#96]
I am using multiple elements.
When i create createToken, it is working well.
But if i try with createPaymentMethod like as createToken, it is giving error.

 import { createPaymentMethod } from 'vue-stripe-elements-plus'

 onSubmit(){
                    createPaymentMethod()
                        .then(
                            data=>{
                                console.log(data)
                            },
                            error=>{
                                console.log(error);
                            }
                        )
}

it is giving error:

vendor.js:112680 [Vue warn]: Error in v-on handler: "TypeError: Object(...) is not a function"

**Comment by PabloGBarcelo** [comment]
Invalid value for createPaymentMethod: value should be object.
Need to attach object like:
createPaymentMethod({
    type: 'card',
    card: cardElement, (obtained from createToken())
    billing_details: {
      name: 'Jenny Rosen',
    },
  })

**Comment by mastashake08** [comment]
I also have the same issue

**Comment by BaiMaoLi** [comment]
I could fix that.
You can use token in createPaymentMethod.
So, first get token, and create payment method by using that token.

**Comment by corbin88** [comment]
@BaiMaoLi, how?

**Comment by MarceauKa** [comment]
@corbin88 

First:
```js
createToken({
    name: this.name
}).then(data => {
    this.card = data.token.card
})
```
Then:
```js
// where this.card.id is the token
createPaymentMethod('card', this.card.id).then(data => {
    // data is your paymentMethod object
})
```

**Comment by LeCoupa** [comment]
@MarceauKa I am not sure the name will be sent with your code above. Can you confirm it is working on your side?

**Comment by LeCoupa** [comment]
Does it work for you when the name is set like this? It does not seem to be saved by Stripe with the 424242**** test card. Can you confirm it is working on your side?

**Comment by MarceauKa** [comment]
@LeCoupa You're right, this works:
```js
createPaymentMethod('card', {
    card: this.card.id, // token from createToken (without any params)
    billing_details: {
        name: this.name, // cardholder name
        address: { // address fetched from algolia places
            line1: this.address.name,
            country: this.address.country,
            city: this.address.city,
            postal_code: this.address.post,
        },
    }
)
```

**Comment by LeCoupa** [comment]
@MarceauKa Thank you it is now working.

```javascript
        const { token } = await createToken()

          const { paymentMethod } = await createPaymentMethod('card', {
            card: token.card.id,
            billing_details: {
              name: this.form.fullName,
              email: this.user.email
            }
          })
```

**Comment by shaunthambyah** [comment]
For anyone struggling with this, this example might be helpful:

`pay() {
      createToken().then(data => {
        if ("error" in data) {
          // handle any errors
          this.stripeErr = data.error.message;
        }
        if ("token" in data) {
          // we've received a token, use the card id to create a payment intent
          createPaymentMethod('card', {
            card: data.token.card.id,
            billing_details: {
              email: this.email
              // you could add more here according to thr stripe docs
            }
          }).then(data => {
            if ("error" in data) {
              // handle any create payment intent errors
              this.stripeErr = data.error.message;
            }
            if ("paymentMethod" in data) {
              // we've received a payment intent in data
              // continue with the rest of your charge
            }
          });
        }
      });
    },`

**Comment by pokerclubtools** [comment]
@jahid56 I ran into the same problem and realized that it was because I was on an old version of the `vue-stripe-elements-plus` package. Try `yarn upgrade vue-stripe-elements-plus`.
